### ISSUE TITLE
update types error without sortKey table

### ISSUE THREAD

**Issue by terrierscript** [neuledge/ddb-table#104]
Thank you for great library.

I try to use `update` without `sortKey`

```ts
const table = new Table<SomeScheme, "Id">

const update = table.update(10)
```

But `table.update` got typescript error

```
Expected 2 arguments, but got 1.
```

FYI: I try modify typescript directly like this, and this error suppressed

```ts
export declare type TableKeyArgs<T, H extends keyof T, S extends keyof T = never> = [
  S
] extends [never] ? [T[H], undefined?] : [T[H], T[S]]
```

**Comment by moshest** [comment]
Thank you for reporting. I deploy a fix on `v1.3.1`
