### ISSUE TITLE
Nulling out conditions and values ?

### ISSUE THREAD

**Issue by jpbelang** [neuledge/ddb-table#48]
I can't seem to run simple examples and the problem seems to be around this bit of code in the javascript in your code (which isn't in your Typescript code):

In PutQuery.js from the library, the constructor looks like this:
```
 constructor(client, params) {
    super(client.put.bind(client), params);
    this.values = void 0;
    this.conditions = void 0;
  }
```

This nulls out the conditions and values after the `handleInputUpdated()` method is called which prevents both adding a condition to work around it or leaving it blank.

I'm relatively new to TypeScript, so maybe I'm making a mistake in my reading of the code.

Thanks.

**Comment by jpbelang** [comment]
Maybe somewhere around this ?

https://github.com/babel/babel/issues/7644

**Comment by moshest** [comment]
Thanks! fixed.
